# Generated by Django 4.1 on 2022-09-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FifthLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('midname', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('AceptanceDate', models.DateTimeField()),
                ('pay', models.IntegerField()),
                ('had_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FirstLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('midname', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('AceptanceDate', models.DateTimeField()),
                ('pay', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FourthLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('midname', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('AceptanceDate', models.DateTimeField()),
                ('pay', models.IntegerField()),
                ('had_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('midname', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('AceptanceDate', models.DateTimeField()),
                ('pay', models.IntegerField()),
                ('had_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ThirdLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('midname', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('AceptanceDate', models.DateTimeField()),
                ('pay', models.IntegerField()),
                ('had_id', models.IntegerField()),
            ],
        ),
    ]
