# Generated by Django 4.1 on 2022-09-06 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StaffView', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fifthlevel',
            name='had_id',
        ),
        migrations.RemoveField(
            model_name='fourthlevel',
            name='had_id',
        ),
        migrations.RemoveField(
            model_name='secondlevel',
            name='had_id',
        ),
        migrations.RemoveField(
            model_name='thirdlevel',
            name='had_id',
        ),
        migrations.AddField(
            model_name='fifthlevel',
            name='had',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StaffView.fourthlevel'),
        ),
        migrations.AddField(
            model_name='fourthlevel',
            name='had',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StaffView.thirdlevel'),
        ),
        migrations.AddField(
            model_name='secondlevel',
            name='had',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StaffView.firstlevel'),
        ),
        migrations.AddField(
            model_name='thirdlevel',
            name='had',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StaffView.secondlevel'),
        ),
        migrations.AlterField(
            model_name='fifthlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='firstlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fourthlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='secondlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thirdlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
