# Generated by Django 4.1 on 2022-09-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffView', '0002_remove_fifthlevel_had_id_remove_fourthlevel_had_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifthlevel',
            name='AceptanceDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='firstlevel',
            name='AceptanceDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fourthlevel',
            name='AceptanceDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='secondlevel',
            name='AceptanceDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='thirdlevel',
            name='AceptanceDate',
            field=models.DateField(),
        ),
    ]
